Repository sktime/skbase, pull requests merged in 2024-02, with the labels that each got.

#284 [ENH] allow arbitrary base class in `all_objects`
  skbase/lookup/_lookup.py
Labels: enhancement

#285 [ENH] estimator soft dependency check utilities
  skbase/tests/conftest.py
  skbase/utils/dependencies/__init__.py
  skbase/utils/dependencies/_dependencies.py
Labels: enhancement

#294 [MNT] add yarnabrina to `all-contributorsrc`
  .all-contributorsrc
Labels: maintenance

#292 [DOC] remove accidental duplicated section in `get_test_params` docstring
  skbase/base/_base.py
Labels: documentation

#281 [MNT] Refactor `.clone()`
  skbase/base/_base.py
  skbase/tests/conftest.py
Labels: enhancement

#296 [MNT] add `codecov` config `yml`, remove CI failure condition
  .codecov.yml
Labels: maintenance

#297 Release 0.7.3
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release
