Repository sktime/skbase, pull requests merged in 2024-08, with the labels that each got.

#345 [ENH] sync dependency checkers with `sktime`
  skbase/tests/conftest.py
  skbase/utils/dependencies/_dependencies.py
Labels: maintenance, enhancement

#346 Release 0.8.2
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release

#347 [MNT] Move release CI to macos-12 image
  .github/workflows/wheels.yml
  docs/source/user_documentation/changelog.rst
Labels: maintenance

#349 [MNT] release workflow: Upgrade deprecated pypa action parameter
  .github/workflows/wheels.yml
Labels: maintenance

#350 [ENH] StderrMute
  skbase/tests/conftest.py
  skbase/utils/stderr_mute.py
  skbase/utils/tests/test_std_mute.py
Labels: enhancement

#352 &toandaominh1997 [BUG] fix dependency checkers in case of multiple distributions available in environment, e.g., on databricks
  skbase/utils/dependencies/_dependencies.py
Labels: bug

#353 [ENH] safer `get_fitted_params` default functionality to avoid exception on `getattr`
  skbase/base/_base.py
Labels: enhancement

#354 Release 0.8.3
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release

#355 [MNT] 0.9.0 deprecations and change actions
  skbase/lookup/_lookup.py
  skbase/lookup/tests/test_lookup.py
  skbase/tests/conftest.py
Labels: maintenance, release

#356 Release 0.9.0
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release
