Repository sktime/skbase, pull requests merged in 2024-01, with the labels that each got.

#260 [BUG] fix `deep_equals` plugin for `pd.Index`
  skbase/utils/deep_equals/_deep_equals.py
  skbase/utils/tests/test_deep_equals.py
Labels: bug, implementing framework

#259 [ENH] retain config at `reset`, add tests for `set_config`, `get_config`
  skbase/base/_base.py
  skbase/tests/test_base.py
Labels: bug, implementing framework

#262 [DOC] readme - version 0.6.2 update
  README.md
Labels: documentation

#261 Release 0.7.0
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: release

#263 [BUG] fix `deep_equals` for `np.array` with `dtype="object"`
  skbase/utils/deep_equals/_deep_equals.py
  skbase/utils/tests/test_deep_equals.py
Labels: bug, implementing framework

#265 Release 0.7.1
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: release

#266 Release 0.7.1 changelog
  docs/source/user_documentation/changelog.rst
Labels: release

#267 [DOC] lint changelog
  docs/source/user_documentation/changelog.rst
Labels: documentation

#275 [BUG] Fix cloning of config for nested objects
  .all-contributorsrc
  skbase/base/_base.py
  skbase/tests/test_base.py
Labels: bug

#273 [ENH] `all_objects` `filter_tags` to function with list-of tags
  skbase/lookup/_lookup.py
Labels: implementing framework, enhancement

#277 [MNT] Adjust `.gitignore`
  .all-contributorsrc
  .gitignore
Labels: ci / build

#268 [ENH] Random state handling, `set_random_state` method
  skbase/base/_base.py
  skbase/tests/conftest.py
  skbase/utils/__init__.py
  skbase/utils/random_state.py
  skbase/utils/tests/test_iter.py
  skbase/utils/tests/test_nested_iter.py
  skbase/utils/tests/test_random_state.py
  skbase/utils/tests/test_utils.py
Labels: implementing framework, enhancement

#278 Release 0.7.2
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: release
