Repository sktime/skbase, pull requests merged in 2024-09, with the labels that each got.

#359 [ENH] add test that html repr of objects does not crash
  skbase/testing/test_all_objects.py
Labels: tests

#362 [ENH] `clone` method to handle nested `dict`
  skbase/base/_base.py
Labels: implementing framework, enhancement

#360 [MNT] 0.10.0 deprecations and change actions
  skbase/utils/dependencies/_dependencies.py
Labels: maintenance, release

#293 [DOC] Replace use of "estimator" term in base object interfaces with more general references
  .all-contributorsrc
  skbase/base/_base.py
Labels: documentation

#361 Release 0.10.0
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release

#363 Release 0.10.0 - changelog
  docs/source/user_documentation/changelog.rst
Labels: maintenance, release

#366 [MNT] updates `sklearn` soft dependency checks to use PEP 440 name
  skbase/base/_pretty_printing/tests/test_pprint.py
  skbase/tests/test_base.py
  skbase/utils/tests/test_deep_equals.py
Labels: maintenance

#365 [MNT] python 3.13 wheels and 3.13-rc.2 testing
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance, release

#368 Release 0.10.1
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release
