Repository sktime/skbase, pull requests merged in 2025-01, with the labels that each got.

#390 Release 0.12.1
  .all-contributorsrc
  README.md
  docs/source/_static/switcher.json
  docs/source/user_documentation/changelog.rst
  pyproject.toml
  skbase/__init__.py
Labels: maintenance, release

#394 Update Contributors List and Badge
  .all-contributorsrc
  CONTRIBUTORS.md
  README.md
Labels: documentation

#392 [ENH] refactor repetitive clone tests with pytest.mark.parametrize, fixes #170
  .all-contributorsrc
  skbase/tests/test_base.py
Labels: tests, enhancement
