Repository sktime/skbase, pull requests merged in 2025-03, with the labels that each got.

#402 [DOC] minor typo fix in code comment
  skbase/_nopytest_tests.py
Labels: documentation

#405 [DOC] minor documentation fixes
  skbase/base/_base.py
  skbase/testing/test_all_objects.py
Labels: documentation

#404 [MNT] remove `tj-actions`
  .github/workflows/test.yml
  .github/workflows/wheels.yml
Labels: maintenance

#407 [BUG] fix `deep_equals` for `pandas.Index`
  skbase/utils/deep_equals/_deep_equals.py
  skbase/utils/tests/test_deep_equals.py
Labels: bug, implementing framework
